//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RecordPlayerSoftWare.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RECORDPLAYERSOFTWARE_DIALOG 102
#define IDS_SETTINGDLG_FILEPATH_STR     102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_LOGINDLG_STR1               104
#define IDS_LOGINDLG_STR2               105
#define IDS_ABOUTDLG_STR1               106
#define IDS_ABOUTDLG_STR2               107
#define IDR_MAINFRAME                   128
#define IDR_SMF                         129
#define IDR_TRAY                        132
#define IDI_PLAY                        133
#define IDI_PLAYPRESS                   134
#define IDI_PlayBack                    135
#define IDI_PlayBackPress               136
#define IDI_PlayNext                    137
#define IDI_PlayNextPress               138
#define IDI_PAUSE                       139
#define IDI_PAUSEPRESS                  140
#define IDI_Sound                       141
#define IDI_SoundMute                   142
#define IDB_BITMAP_VOL_OFF              143
#define IDB_BITMAP_VOL_ON               144
#define IDB_BITMAP_THUMB                145
#define IDB_BITMAP_ACTIVE               146
#define IDB_BITMAP1                     147
#define IDB_BITMAP_NORMAL               147
#define IDD_PlayerShowDlg               148
#define IDD_DownLoadListShowDlg         149
#define IDR_MENU_SHOW_DOWNLOAD_FILE     150
#define IDD_QueryRecordDBDlg            152
#define IDB_TICK                        153
#define IDI_Setting                     154
#define IDI_SettingPress                155
#define IDD_SettingDlg                  156
#define IDI_Login                       157
#define IDI_LoginPress                  158
#define IDI_DownLoad                    159
#define IDI_DownLoadPress               160
#define IDI_Query                       161
#define IDI_QueryPress                  162
#define IDD_PlayerListShowDlg           163
#define IDI_DevIcon                     165
#define IDI_TunnelIcon                  166
#define IDD_AddDevDlg                   167
#define IDR_MENU_DEV_TREE               169
#define IDI_MainPage                    170
#define IDI_MainPagePress               172
#define IDB_SmallDownLoad               173
#define IDB_BITMAP2                     174
#define IDB_PauseDownLoad               174
#define IDR_MENU_DEV_LIST               175
#define IDD_ShowTipInfoDlg              176
#define IDI_Edit                        177
#define IDI_AddDev                      178
#define IDI_DelDev                      179
#define IDD_LOGINDLG                    180
#define IDC_MainBtnRect                 1003
#define IDC_ShowRect                    1004
#define IDC_DownLoadList                1017
#define IDC_StartDate                   1018
#define IDC_StartTime                   1019
#define IDC_EndDate                     1020
#define IDC_EndTime                     1021
#define IDC_SettingBtn                  1022
#define IDC_FileSavePath                1023
#define IDC_FileOpenBtn                 1024
#define IDC_IPADDRESS1                  1025
#define IDC_EDIT2                       1026
#define IDC_DownLoadBtn                 1028
#define IDC_QueryBtn                    1029
#define IDC_PlayerList                  1030
#define IDC_Device_Tree                 1031
#define IDC_Device_List                 1032
#define IDC_AddDevBtn                   1034
#define IDC_DeleteDevBtn                1035
#define IDC_DevName                     1036
#define IDC_DevPort                     1037
#define IDC_DevID                       1038
#define IDC_DevIP                       1039
#define IDC_DATE_START                  1041
#define IDC_TIME_START                  1042
#define IDC_DATE_END                    1043
#define IDC_TIME_END                    1044
#define IDC_QueryRecordBtn              1045
#define IDC_DevCombox                   1047
#define IDC_ChannelCombox               1048
#define IDC_DevStatic                   1049
#define IDC_ChannelStatic               1050
#define IDC_StartStatic                 1051
#define IDC_EndStatic                   1052
#define IDC_QueryStatic                 1053
#define IDC_TimeSelectStatic            1054
#define IDC_PlayBtn                     1055
#define IDC_PlayerStatic                1056
#define IDC_PlayBackBtn                 1057
#define IDC_PlayNextBtn                 1058
#define IDC_SoundCtrlBtn                1059
#define IDC_SoundVolume                 1060
#define IDC_PlayProGressBtn             1061
#define IDC_PlayTimeShow                1062
#define IDC_InfoText                    1063
#define IDC_BUTTON1                     1064
#define IDC_InfoICON                    1064
#define IDC_EditBtn                     1064
#define IDC_ShowVol                     1065
#define IDC_ShowVolSpectrum             1065
#define IDC_ConnectText                 1066
#define IDC_BatchDownBtn                1068
#define IDC_BUTTON2                     1069
#define IDC_ComBo_RECORDTYPE            1072
#define IDC_NEWUSERNAME                 1075
#define IDC_NEWPASSWORD                 1076
#define IDC_NEWPASSWORD2                1077
#define IDC_SHOW_VERSION                5050
#define IDC_LoginBtn                    6001
#define IDC_CancelBtn                   6002
#define IDC_UserNameEdit                6003
#define IDC_PASSWORDEDIT                6004
#define IDS_RECORDPLAYERSOFTWARE_DIALOG 8000
#define IDS_MENUITEM_TRAY_OPEN          8001
#define IDS_MENUITEM_TRAY_CLOSE         8002
#define IDC_ShowDevBtn                  9001
#define ID_TRAY                         32771
#define ID_TRAY_32772                   32772
#define ID_MENUITEM_TRAY_OPEN           32773
#define ID_TRAY_32774                   32774
#define ID_MENUITEM_TRAY_CLOSE          32775
#define ID_32776                        32776
#define ID_LoadRecordDB                 32777
#define ID_32778                        32778
#define ID_DownLoadFile                 32779
#define ID_32780                        32780
#define ID_Menu                         32781
#define ID_Menu32782                    32782
#define ID_StopDownLoad                 32783
#define ID_QueryDownLoadFile            32784
#define ID_32785                        32785
#define ID_DeleteDownLoad               32786
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_AddDev                       32791
#define ID_DelDev                       32792
#define ID_ModifyDev                    32793
#define ID_32794                        32794
#define ID_ShowRecordDB                 32795
#define ID_DownLoadRecordDB             32796
#define ID_32797                        32797
#define ID_32798                        32798
#define ID_32799                        32799
#define ID_PlayRecordFile               32800
#define ID_32801                        32801
#define ID_DownLoadAllFile              32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
